# ============================================================================
# Fractal geometry generators in R (H-tree; see repository for full set)
#
# R companion to the fractal-geometry methodology applied in the article:
#   Lemenkova, P. (2020). Fractal Surfaces of Synthetical DEM Generated by
#   GRASS GIS Module r.surf.fractal from ETOPO1 Raster Grid.
#   Journal of Geodesy and Geoinformation, 7(2), 86-102.
#   DOI:      https://doi.org/10.9733/JGG.2020R0006.E
#   figshare: https://doi.org/10.6084/m9.figshare.13047815
#   HAL:      https://hal.science/hal-02956736
#   Zenodo:   https://zenodo.org/record/4064662
#   SSRN:     http://ssrn.com/abstract=3704194
#
# In that study the fractal DEM surfaces were synthesised in GRASS GIS with the
# r.surf.fractal module from an ETOPO1 grid. These R scripts explore the
# underlying fractal-geometry algorithms (self-similarity, iterative/recursive
# generation, escape-time and IFS methods, fractal dimension).
#
# Author: Polina Lemenkova  |  ORCID: 0000-0002-5759-1089
# ============================================================================

#Generate H-Fractals with ggplot The code below starts with setting the initial variables and defines the first line in a data frame. The data frame holds the start and end coordinates and the iteration number.

 library(ggplot2)
 ## H-Fractal Parameters
 p <- 8 ## Number of iterations
 a <- 1 / sqrt(2) ## Shortening parameter
 
 ## Define horizontal starting line
 h_fractal <- data.frame(x1 = -1,
                         y1 = 0,
                         x2 = 1,
                         y2 = 0,
                         m = 0)

The loop defines the iterations and adds a new row to the data frame for each line. First, the direction flips by setting the dx and dy values to either 0 or 1. The second part defines the row numbers for the previously defined lines and the new lines. The code then calculates the coordinates for the new line segments.

 # Generate coordinates (each line on a row)
 for (m in 1:p) {
   ## Flip direction
   dx <- (m - 1) %% 2
   dy <- m %% 2
   # Previous and current line numbers
   i <- (2^(m - 1)):(2^m - 1)
   j <- (2^m):(2^(m + 1) - 1)
   ## Calculate coordinates
   h_fractal[j, "x1"] <- c(h_fractal[i, "x1"] - dx * a^m, h_fractal[i, "x2"] - dx * a^m)
   h_fractal[j, "x2"] <- c(h_fractal[i, "x1"] + dx * a^m, h_fractal[i, "x2"] + dx * a^m)
   h_fractal[j, "y1"] <- c(h_fractal[i, "y1"] - dy * a^m, h_fractal[i, "y2"] - dy * a^m)
   h_fractal[j, "y2"] <- c(h_fractal[i, "y1"] + dy * a^m, h_fractal[i, "y2"] + dy * a^m)
   ## Set line property
   h_fractal[j, "m"] <- m
 }

Lastly, The fractal is visualised with ggplot and the line segment geometry. The colour of the line slowly fades by setting it to the iteration number.

   ## Visualise
 ggplot(h_fractal) +
   aes(x = x1, y = y1, xend = x2, yend = y2,
       col = m) +
   geom_segment(size = .5) +
   scale_size(guide = NULL) +
   scale_colour_gradientn(colours = gray.colors(p), guide = NULL) +
   theme_void()


